name = "astra"
version = "0.0.1"
description = "Astra - facade orb"

[orbs]
astra_value = "path:../astra_value"
astra_outcome = "path:../astra_outcome"
astra_lexer = "path:../astra_lexer"
astra_ast = "path:../astra_ast"
astra_parser = "path:../astra_parser"
astra_check = "path:../astra_check"
astra_eval = "path:../astra_eval"
astra_host = "path:../astra_host"
astra_run = "path:../astra_run"
