[package]
name = "test_parse"
version = "0.1.0"

[orbs]
astra_run = "path:../orbs/astra_run"
astra_parser = "path:../orbs/astra_parser"
astra_lexer = "path:../orbs/astra_lexer"
astra_ast = "path:../orbs/astra_ast"
os = "*"
bytes = "*"
